# server 配置
server:
  # HTTP 端口
  port: 28080
  # 应用程序
  servlet:
    context-path: /
  # tomcat 配置
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

# spring 配置
spring:
  # 服务模块
  devtools:
    restart:
      # 热部署
      enabled: true
  # 数据源配置
  datasource:
    # 动态数据源
    dynamic:
      # 主数据源
      primary: test
      datasource:
        test:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/user_role_menu?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
  # redis 配置
  redis:
    database: 8
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60000

# token 配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis 配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.perms.demo.app.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 日志配置
logging:
  level:
    com.perms: debug
    org.springframework: warn


